namespace Rsse.Tooling.Scripts;

/// <summary>
/// Инициализация данных для Postgres.
/// </summary>
public static class NpgsqlScript
{
    /// <summary>
    /// DDL и первоначальные данные для авторизации на Postgres.
    /// В скрипте присутствуют ограничения на длину строк.
    /// </summary>
    public const string DdlData = """
                                  CREATE TABLE IF NOT EXISTS "Note" (
                                    "NoteId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    "Title" varchar(50) NOT NULL,
                                    "Text" varchar(10000) NOT NULL,
                                    PRIMARY KEY ("NoteId"),
                                    UNIQUE ("Title")
                                  );
                                  CREATE TABLE IF NOT EXISTS "Tag" (
                                    "TagId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    "Tag" varchar(30) NOT NULL,
                                    PRIMARY KEY ("TagId"),
                                    UNIQUE ("Tag")
                                  );
                                  CREATE TABLE IF NOT EXISTS "TagsToNotes" (
                                    "TagId" integer NOT NULL,
                                    "NoteId" integer NOT NULL,
                                    PRIMARY KEY ("TagId", "NoteId"),
                                    FOREIGN KEY ("NoteId") REFERENCES "Note"("NoteId") ON DELETE CASCADE,
                                    FOREIGN KEY ("TagId") REFERENCES "Tag"("TagId") ON DELETE CASCADE
                                  );
                                  CREATE TABLE IF NOT EXISTS public."Users" (
                                     "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     "Email" varchar(30) NOT NULL,
                                     "Password" varchar(30) NOT NULL,
                                     PRIMARY KEY ("Id")
                                  );
                                  INSERT INTO public."Users" ("Id", "Email", "Password")
                                  VALUES (1, '1@2', '12')
                                  ON CONFLICT ("Id") DO NOTHING;
                                  """;

    /// <summary>
    /// DDL будет содержать таблицу "Users".
    /// Именования берутся в кавычки для сохранения регистра.
    /// К ключу дописывается автогенерация.
    /// </summary>
    public const string CreateDdl = """
                                    WITH table_info AS (
                                      SELECT
                                        t.table_name,
                                        (
                                          SELECT string_agg(
                                            '  "' || c.column_name || '" ' ||
                                            CASE
                                              WHEN a.attidentity IN ('a', 'd') THEN
                                                c.data_type || ' GENERATED ' ||
                                                CASE WHEN a.attidentity = 'a' THEN 'ALWAYS' ELSE 'BY DEFAULT' END ||
                                                ' AS IDENTITY'
                                              WHEN c.data_type = 'character varying' THEN 'varchar(' || c.character_maximum_length || ')'
                                              WHEN c.data_type = 'numeric' THEN 'numeric(' || c.numeric_precision || ',' || c.numeric_scale || ')'
                                              ELSE c.data_type
                                            END ||
                                            CASE WHEN c.is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END ||
                                            CASE
                                              WHEN c.column_default IS NOT NULL AND a.attidentity = '' THEN
                                                ' DEFAULT ' || c.column_default
                                              ELSE ''
                                            END,
                                            E',\n' ORDER BY c.ordinal_position
                                          )
                                          FROM information_schema.columns c
                                          JOIN pg_namespace n ON n.nspname = c.table_schema
                                          JOIN pg_class cl ON cl.relnamespace = n.oid AND cl.relname = c.table_name
                                          JOIN pg_attribute a ON a.attrelid = cl.oid
                                                             AND a.attname = c.column_name
                                                             AND NOT a.attisdropped
                                          WHERE c.table_name = t.table_name
                                            AND c.table_schema = t.table_schema
                                        ) AS columns,
                                        (
                                          SELECT string_agg(
                                            CASE
                                              WHEN tc.constraint_type = 'PRIMARY KEY' AND NOT EXISTS (
                                                SELECT 1 FROM pg_constraint pc
                                                WHERE pc.conname = tc.constraint_name AND pc.contype = 'u'
                                              ) THEN
                                                '  PRIMARY KEY ("' || (
                                                  SELECT string_agg(kcu.column_name, '", "' ORDER BY kcu.ordinal_position)
                                                  FROM information_schema.key_column_usage kcu
                                                  WHERE kcu.constraint_name = tc.constraint_name
                                                ) || '")'
                                              WHEN tc.constraint_type = 'FOREIGN KEY' THEN
                                                '  ' || pg_get_constraintdef(pc.oid)
                                              WHEN tc.constraint_type = 'UNIQUE' THEN
                                                '  UNIQUE ("' || (
                                                  SELECT string_agg(kcu.column_name, '", "' ORDER BY kcu.ordinal_position)
                                                  FROM information_schema.key_column_usage kcu
                                                  WHERE kcu.constraint_name = tc.constraint_name
                                                ) || '")'
                                              WHEN tc.constraint_type = 'CHECK' AND
                                                   NOT (cc.check_clause ~ 'IS NOT NULL' AND c.is_nullable = 'NO') THEN
                                                '  CHECK (' || cc.check_clause || ')'
                                            END,
                                            E',\n'
                                          )
                                          FROM information_schema.table_constraints tc
                                          LEFT JOIN pg_constraint pc ON tc.constraint_name = pc.conname
                                          LEFT JOIN information_schema.check_constraints cc ON tc.constraint_name = cc.constraint_name
                                          LEFT JOIN information_schema.columns c ON
                                            tc.table_name = c.table_name AND
                                            tc.table_schema = c.table_schema AND
                                            c.column_name = regexp_replace(split_part(tc.constraint_name, '_', 2), '^[0-9]+', '')
                                          WHERE tc.table_name = t.table_name
                                            AND tc.table_schema = t.table_schema
                                            AND tc.constraint_type IN ('PRIMARY KEY', 'FOREIGN KEY', 'UNIQUE', 'CHECK')
                                        ) AS constraints,
                                        EXISTS (
                                          SELECT 1 FROM information_schema.table_constraints tc
                                          JOIN information_schema.constraint_column_usage ccu ON tc.constraint_name = ccu.constraint_name
                                          WHERE tc.table_name = t.table_name AND tc.constraint_type = 'FOREIGN KEY'
                                        ) AS has_dependencies
                                      FROM information_schema.tables t
                                      WHERE t.table_schema = 'public'
                                        AND t.table_type = 'BASE TABLE'
                                        -- AND t.table_name != 'Users'  -- Исключаем таблицу "Users"
                                    )

                                    SELECT
                                      'DROP TABLE IF EXISTS "' || table_name || '" CASCADE;' || E'\n' ||
                                      'CREATE TABLE "' || table_name || '" (' || E'\n' ||
                                      columns ||
                                      CASE WHEN constraints IS NOT NULL THEN E',\n' || constraints ELSE '' END ||
                                      E'\n);' || E'\n'
                                    FROM table_info
                                    ORDER BY has_dependencies::int, table_name;
                                    """;
}
