export const RouteConstants = {
  accountLoginGetUrl: "/account/login",
  accountLogoutGetUrl: "/account/logout",
  accountCheckGetUrl: "/account/check",
  accountUpdateGetUrl: "/account/update",
  catalogPageGetUrl: "/api/catalog",
  catalogNavigatePostUrl: "/api/catalog",
  catalogDeleteNoteUrl: "/api/catalog",
  complianceIndicesGetUrl: "/api/compliance/indices",
  createGetTagsAuthorizedUrl: "/api/create",
  createNotePostUrl: "/api/create",
  migrationCopyGetUrl: "/migration/copy",
  migrationCreateGetUrl: "/migration/create",
  migrationRestoreGetUrl: "/migration/restore",
  migrationUploadPostUrl: "/migration/upload",
  migrationDownloadGetUrl: "/migration/download",
  readElectionGetUrl: "/api/read/election",
  readTitleGetUrl: "/api/read/title",
  readGetTagsUrl: "/api/read",
  readNotePostUrl: "/api/read",
  updateGetNoteWithTagsUrl: "/api/update",
  updateNotePostUrl: "/api/update",
  systemVersionGetUrl: "/system/version"
} as const;
