export const RouteConstants = {
  complianceIndicesGetUrl: "/v6/compliance/indices",
  catalogPageGetUrl: "/v6/catalog",
  catalogNavigatePostUrl: "/v6/catalog/navigate",
  noteDeleteUrl: "/v6/note/delete",
  createNotePostUrl: "/v6/note/create",
  updateNotePostUrl: "/v6/note/update",
  readElectionGetUrl: "/v6/election/switch",
  readTitleGetUrl: "/v6/title",
  readTagsGetUrl: "/v6/tags",
  readNotePostUrl: "/v6/election/note",
  readTagsForCreateAuthGetUrl: "/v6/tags/forCreate",
  redNoteWithTagsForUpdateAuthGetUrl: "/v6/note/forUpdate",
  accountLoginGetUrl: "/v6/account/login",
  accountLogoutGetUrl: "/v6/account/logout",
  accountCheckGetUrl: "/v6/account/check",
  accountUpdateGetUrl: "/v6/account/update",
  migrationCopyGetUrl: "/migration/copy",
  migrationCreateGetUrl: "/migration/create",
  migrationRestoreGetUrl: "/migration/restore",
  migrationUploadPostUrl: "/migration/upload",
  migrationDownloadGetUrl: "/migration/download",
  systemVersionGetUrl: "/system/version"
} as const;
