apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.version: "v6.0.3"
    manifest.version: "2025-06-25"
  name: rsse-app-deployment
  labels:
    app: rsse-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsse-app
  template:
    metadata:
      labels:
        app: rsse-app
    spec:
      containers:
        - name: rsse-app
          image: nick219nick/rsse-app
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RSSE_APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['app.version']

            # Переменные инициализации профайлера из файла `v2.env.pwd`
            # Документация: https://grafana.com/docs/pyroscope/next/configure-client/language-sdks/dotnet/#send-data-to-pyroscope-oss-or-grafana-cloud-profiles
            # Создать секрет: kubectl create secret generic pyroscope-secret --from-file=PYROSCOPE_BASIC_AUTH_PASSWORD=./pyroscope.secret.pwd (содержимое файла: токен)
            - name: PYROSCOPE_BASIC_AUTH_USER
              value: "1031458"
            - name: PYROSCOPE_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pyroscope-secret
                  key: PYROSCOPE_BASIC_AUTH_PASSWORD
            - name: PYROSCOPE_SERVER_ADDRESS
              value: "https://profiles-prod-001.grafana.net"
            # Подойдут ли строки?
            - name: CORECLR_ENABLE_PROFILING
              value: "1"
            - name: CORECLR_PROFILER
              value: "{BD1A650D-AC5D-4896-B64F-D6FA25D6B26A}"
            - name: CORECLR_PROFILER_PATH
              value: "/App/Pyroscope.Profiler.Native.so"
            - name: LD_PRELOAD
              value: "/App/Pyroscope.Linux.ApiWrapper.x64.so"
            - name: PYROSCOPE_APPLICATION_NAME
              value: "rsse-app"
            - name: PYROSCOPE_PROFILING_ENABLED
              value: "1"

          volumeMounts:
          - mountPath: /root/.aspnet/DataProtection-Keys
            name: dataprotection-keys
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /system/live
              port: 5000
            periodSeconds: 30
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /system/ready
              port: 5000
            periodSeconds: 30
            initialDelaySeconds: 30
      volumes:
        - name: dataprotection-keys
          persistentVolumeClaim:
            claimName: dataprotection-keys-pvc
---
