apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-access
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-access-binding
subjects:
- kind: ServiceAccount
  name: metrics-reader
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: metrics-access
  apiGroup: rbac.authorization.k8s.io
# TOKEN=$(kubectl -n kube-system create token metrics-reader)
# curl -k -H "Authorization: Bearer $TOKEN" https://localhost:10250/metrics/cadvisor