##########################################################################
FROM mcr.microsoft.com/dotnet/sdk:9.0.202-alpine3.21-amd64 AS build-env
WORKDIR /app

# при использовании CPM файл версионирования необходимо скопировать в контейнер
COPY Directory.Packages.props .
COPY ./Rsse.Service/ ./Rsse.Service/
COPY ./Rsse.Data/ ./Rsse.Data/
COPY ./Rsse.Domain/ ./Rsse.Domain/
# скопируем функционал токенизатора
COPY ./Rsse.Engine.Tokenizer ./Rsse.Engine.Tokenizer
COPY ./Rsse.Engine.VectorSearch ./Rsse.Engine.VectorSearch
# скопируем предварительно собранный фронт
COPY ./Rsse.Client/ClientApp/build/ ./Rsse.Service/ClientApp/build/

WORKDIR /app/Rsse.Service
# опубликуем в папку /app/Rsse.Service/out/
RUN dotnet publish -c Release -r linux-musl-x64 -o out Rsse.Service.csproj

################
FROM alpine:3.19
LABEL org.opencontainers.image.description="RSSearchEngine: .NET"
# пакеты для запуска
RUN apk add --no-cache libstdc++ libgcc
# apk для глобализации (отключена в csproj): icu-libs

COPY --from=build-env /app/Rsse.Service/out/ App/
COPY --from=build-env /app/Rsse.Service/ClientApp/build/ App/ClientApp/build/
WORKDIR /App
EXPOSE 5000
ENTRYPOINT ["./Rsse.Service"]
