version: "3.7"

services:

  mysql:
    image: mysql:8.0.31
    container_name: mysql_t
    environment:
      - MYSQL_USER=1
      - MYSQL_PASSWORD=1
      - MYSQL_DATABASE=tagit
      - MYSQL_ROOT_PASSWORD=1
    restart: always
    expose:
      - 3306
    volumes:
      - mysql-volume:/var/lib/mysql

  tagit:
    build: .
    container_name: tagit
    restart: always
    ports:
      - 5000:5000

volumes:
  mysql-volume:
