###################################
FROM node:21-slim AS node-build-env
WORKDIR /home/node/app
COPY ./Rsse.Front/ClientApp/*.json ./
COPY ./Rsse.Front/ClientApp/src/ ./src
COPY ./Rsse.Front/ClientApp/public/ ./public
RUN npm install
RUN npm run build

##################################################
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

# CPM: копируем файл версионирования
COPY Directory.Packages.props .
COPY ./Rsse.Base/ ./Rsse.Base/
COPY ./Rsse.Data/ ./Rsse.Data/

# JS: копируем папку с файлами фронта
# COPY ./Rsse.Front/ClientApp/build/ ./Rsse.Base/ClientApp/build/
COPY --from=node-build-env /home/node/app/build/ ./Rsse.Base/ClientApp/build/

WORKDIR /app/Rsse.Base
# .NET: публикуем в папку /app/Rsse.Base/out/
RUN dotnet publish -c Release -o out

########################################
FROM mcr.microsoft.com/dotnet/aspnet:7.0
COPY --from=build-env /app/Rsse.Base/out/ App/
COPY --from=build-env /app/Rsse.Base/ClientApp/build/ App/ClientApp/build/
WORKDIR /App
EXPOSE 5000
ENTRYPOINT ["dotnet", "Rsse.Base.dll"]
