FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build-env
WORKDIR /app

# при использовании CPM файл версионирования необходимо скопировать в контейнер
COPY Directory.Packages.props .
COPY ./Rsse.Service/ ./Rsse.Service/
COPY ./Rsse.Data/ ./Rsse.Data/
# скопируем предварительно собранный фронт
COPY ./Rsse.Client/ClientApp/build/ ./Rsse.Service/ClientApp/build/

WORKDIR /app/Rsse.Service
# опубликуем в папку /app/Rsse.Service/out/
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine
LABEL org.opencontainers.image.description="RSSearchEngine: .NET"
COPY --from=build-env /app/Rsse.Service/out/ App/
COPY --from=build-env /app/Rsse.Service/ClientApp/build/ App/ClientApp/build/
WORKDIR /App
EXPOSE 5000
ENTRYPOINT ["dotnet", "Rsse.Service.dll"]
