version: "3.7"
# образ сервиса билдится через докерфайл

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-docker-config.yaml:/etc/otelcol-contrib/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GRAFANA_CLOUD_OTLP_ENDPOINT: "https://otlp-gateway-prod-us-east-0.grafana.net/otlp"
      GRAFANA_CLOUD_INSTANCE_ID: "${GRAFANA_CLOUD_INSTANCE_ID}"
      GRAFANA_CLOUD_API_KEY: "${GRAFANA_CLOUD_API_KEY}"
    networks:
      - default

  mysql:
    image: mysql:8.0.31-debian
    container_name: mysql_rsse
    environment:
      - MYSQL_USER=1
      - MYSQL_PASSWORD=1
      - MYSQL_DATABASE=tagit
      - MYSQL_ROOT_PASSWORD=1
    restart: always
    expose:
      - 3306
    volumes:
      - compose-mysql-volume:/var/lib/mysql
    networks:
      - default

  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres_rsse
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: 1
      POSTGRES_DB: tagit
    expose:
      - 5432
    volumes:
      - compose-pg-volume:/var/lib/postgresql/data
    networks:
      - default

  tagit:
    build:
      context: .
      dockerfile: Dockerfile-net-react
    container_name: rsse
    restart: always
    ports:
      - 5001:5000
    networks:
      - default

volumes:
  compose-mysql-volume:
  compose-pg-volume:
