# manual start: w/profiler
name: Build.Docker.v2

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build --file Dockerfile.net.react.v2 --tag rsse-ci:$(date +%s) .
