# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build.NET

on:
  push:
    branches: [ "master", "feature/**", "develop" ]
    # tags-ignore: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      env:
        POSTGRES_HOST: postgres
        MYSQL_HOST: mysql
      run: dotnet test --no-build --logger "console;verbosity=detailed" --environment "DOTNET_CI=true" -c Release
