# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build.NET

on:
  push:
    branches: [ "master", "feature/**", "develop" ]
    # tags-ignore: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres_test:
        image: postgres:17.4-alpine3.21
        env:
          POSTGRES_PASSWORD: 1
          POSTGRES_USER: 1
          POSTGRES_DB: tagit
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql_test:
        image: mysql:8.0.31-debian
        env:
          MYSQL_USER: 1
          MYSQL_PASSWORD: 1
          MYSQL_DATABASE: tagit
          MYSQL_ROOT_PASSWORD: 1
        ports:
          - 3307:3306
        # options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      env:
        POSTGRES_HOST: postgres_test
        MYSQL_HOST: mysql_test
      run: dotnet test --no-build --logger "console;verbosity=detailed" --environment "DOTNET_CI=true" -c Release
