# manual start
name: Build.Docker

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build --file Dockerfile-net-react --tag rsse-ci:$(date +%s) .
